CREATE TABLE TBL_BOOKS
(
B_CODE	VARCHAR2(20)		PRIMARY KEY,
B_NAME	nVARCHAR2(125)	NOT NULL	,
B_AUTHER	nVARCHAR2(125)	NOT NULL,	
B_COMP	nVARCHAR2(125)		,
B_YEAR	VARCHAR2(10)		,
B_IPRICE	NUMBER		
);

CREATE TABLE TBL_MEMBER
(
M_ID	VARCHAR2(20)	NOT NULL	PRIMARY KEY,
M_PASSWORD	nVARCHAR2(125)	NOT NULL	,
M_LOGIN_DATE	nVARCHAR2(125)		,
M_REM	nVARCHAR2(125)		
);

DROP TABLE TBL_MEMBER;

CREATE TABLE TBL_READ_BOOK
(
RB_SEQ	NUMBER	NOT NULL	PRIMARY KEY,
RB_BCODE	VARCHAR2(20)	NOT NULL	,
RB_DATE	VARCHAR2(10)	NOT NULL	,
RB_STIME	VARCHAR2(10)		,
RB_RTIME	NUMBER(10,3)		,
RB_SUBJECT	nVARCHAR2(20)		,
RB_TEXT	nVARCHAR2(400)		,
RB_STAR	NUMBER		
);

CREATE SEQUENCE seq_tbl_read_book
START WITH 1 INCREMENT BY 1;

ALTER TABLE tbl_read_book MODIFY(rb_text nVARCHAR2(2000));

ALTER TABLE tbl_read_book 
ADD CONSTRAINT fk_bcode FOREIGN KEY (RB_BCODE)
REFERENCES tbl_books(B_CODE) ON DELETE CASCADE;